spring:
  application:
    name: mini-erp

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/minierp
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /mini-erp

logging:
  level:
    com.example.minierp: DEBUG
    org.springframework.security: DEBUG

---
# Profile para teste rápido (sem banco)
spring:
  config:
    activate:
      on-profile: test

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---
# Profile para desenvolvimento com H2 Database (em memória)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:minierp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
