spring:
  application:
    name: mini-erp

  profiles:
    active: h2

  # Configuração para H2 Database (em memória - não precisa de PostgreSQL)
  datasource:
    url: jdbc:h2:mem:minierp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Desabilitar configuração de segurança conflitante
  # security:
  #   user:
  #     name: admin
  #     password: admin123
  #     roles: ADMIN

server:
  port: 8080

logging:
  level:
    com.example.minierp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
